disable `ptr` conversion, due to possible compiler error
This function can trigger a

Error: internal error: genAssignment: tyUncheckedArray

compiler error. For now disable ptr support. It wasn't well supported
so far anyway.